$scriptsPath = "scripts"
if (-not (Test-Path $scriptsPath)) {
    New-Item -ItemType Directory -Path $scriptsPath
}
Set-Location $scriptsPath
git clone "https://github.com/neurotrader888/TechnicalAnalysisAutomation" "TechnicalAnalysisAutomation"
git clone "https://github.com/neurotrader888/TrendLineAutomation" "TrendLineAutomation"
git clone "https://github.com/neurotrader888/TrendlineBreakoutMetaLabel" "TrendlineBreakoutMetaLabel"
git clone "https://github.com/neurotrader888/VolatilityHawkes" "VolatilityHawkes"
git clone "https://github.com/neurotrader888/market-structure" "market-structure"
git clone "https://github.com/neurotrader888/mcpt" "mcpt"
git clone "https://github.com/neurotrader888/TradeDependenceRunsTest" "TradeDependenceRunsTest"
git clone "https://github.com/KVignesh122/AssetNewsSentimentAnalyzer" "AssetNewsSentimentAnalyzer"
git clone "https://github.com/facebook/prophet" "prophet"
git clone "https://github.com/blue-yonder/tsfresh" "tsfresh"
git clone "https://github.com/DynamicsAndNeuralSystems/Catch22" "Catch22"
git clone "https://github.com/FilippoMB/Time-series-classification-and-clustering-with-Reservoir-Computing" "Time-series-classification-and-clustering-with-Reservoir-Computing"
git clone "https://github.com/JerBouma/FinanceToolkit" "FinanceToolkit"
git clone "https://github.com/matplotlib/mplfinance" "mplfinance"
git clone "https://github.com/kernc/backtesting.py" "backtesting.py"
git clone "https://github.com/pmorissette/bt" "bt"
git clone "https://github.com/polakowo/vectorbt" "vectorbt"
git clone "https://github.com/ranaroussi/quantstats" "quantstats"
git clone "https://github.com/kieran-mackle/AutoTrader" "AutoTrader"
git clone "https://github.com/pskrunner14/trading-bot" "trading-bot"
git clone "https://github.com/raminmh/liquid-s4" "liquid-s4"
git clone "https://github.com/BrainInspired/Liquid-Time-Constant-Networks" "Liquid-Time-Constant-Networks"
git clone "https://github.com/google-research/google-research" "google-research"
git clone "https://github.com/quantinfo/ng-rc-paper-code" "ng-rc-paper-code"